name: iterative_convex_hull
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  convex_hull: ^1.1.2
  collection: ^1.18.0

dev_dependencies:
  checks: ^0.3.0
  lints: ^5.0.0
  test: ^1.24.0
